//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.19 at 04:38:05 PM EET 
//


package datacenterInterface.dtos.jaxbBindingClasses;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the datacenterInterface.dtos package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: datacenterInterface.dtos
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServerDescription }
     */
    public ServerDescription createServerDescription() {
        return new ServerDescription();
    }

    /**
     * Create an instance of {@link ServerDiskDescription }
     */
    public ServerDiskDescription createDiskDescription() {
        return new ServerDiskDescription();
    }


    /**
     * Create an instance of {@link ActivityDescription }
     */
    public WorkloadSchedule createWorkloadSchedule() {
        return new WorkloadSchedule();
    }

    /**
     * Create an instance of {@link ActivityDescription }
     */
    public ActivityDescription createActivityDescription() {
        return new ActivityDescription();
    }

    /**
     * Create an instance of {@link ActivityService }
     */
    public ActivityService createActivityService() {
        return new ActivityService();
    }

    /**
     * Create an instance of {@link ActivityDescription }
     */
    public ApplicationDescription createApplicationDescription() {
        return new ApplicationDescription();
    }

    /**
     * Create an instance of {@link VirtualDiskDescription }
     */
    public VirtualDiskDescription createVirtualDiskDescription() {
        return new VirtualDiskDescription();
    }


}
